#!/bin/sh
set -e

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<-EOSQL
  CREATE DATABASE IF NOT EXISTS orderdb;
  CREATE DATABASE IF NOT EXISTS inventorydb;
  CREATE DATABASE IF NOT EXISTS userdb;

  CREATE USER IF NOT EXISTS '${ORDER_DB_USER}'@'%' IDENTIFIED BY '${ORDER_DB_PASSWORD}';
  CREATE USER IF NOT EXISTS '${INVENTORY_DB_USER}'@'%' IDENTIFIED BY '${INVENTORY_DB_PASSWORD}';
  CREATE USER IF NOT EXISTS '${USER_DB_USER}'@'%' IDENTIFIED BY '${USER_DB_PASSWORD}';

  GRANT ALL PRIVILEGES ON orderdb.* TO '${ORDER_DB_USER}'@'%';
  GRANT ALL PRIVILEGES ON inventorydb.* TO '${INVENTORY_DB_USER}'@'%';
  GRANT ALL PRIVILEGES ON userdb.* TO '${USER_DB_USER}'@'%';
  FLUSH PRIVILEGES;
EOSQL
