#!/bin/sh
set -e

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<-EOSQL
  CREATE DATABASE IF NOT EXISTS order_service;
  CREATE DATABASE IF NOT EXISTS inventory_service;
  CREATE DATABASE IF NOT EXISTS user_service;

  CREATE USER IF NOT EXISTS '${ORDER_DB_USER}'@'%' IDENTIFIED BY '${ORDER_DB_PASSWORD}';
  CREATE USER IF NOT EXISTS '${INVENTORY_DB_USER}'@'%' IDENTIFIED BY '${INVENTORY_DB_PASSWORD}';
  CREATE USER IF NOT EXISTS '${USER_DB_USER}'@'%' IDENTIFIED BY '${USER_DB_PASSWORD}';

  GRANT ALL PRIVILEGES ON order_service.* TO '${ORDER_DB_USER}'@'%';
  GRANT ALL PRIVILEGES ON inventory_service.* TO '${INVENTORY_DB_USER}'@'%';
  GRANT ALL PRIVILEGES ON user_service.* TO '${USER_DB_USER}'@'%';
  FLUSH PRIVILEGES;
EOSQL
