spring.application.name=notification-service

server.port=8083

spring.kafka.bootstrap-servers=kafka:9092


# EMAIL CONFIG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kk33334444kk@gmail.com
spring.mail.password=sjhpwjbdtnkquxem

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true