spring.application.name=product_service

# 👇 أهم سطر
spring.kafka.bootstrap-servers=kafka:9092

# 👇 Mongo (عشان تتجنب أي error تاني)
spring.data.mongodb.uri=mongodb://root:secret@mongodb:27017/product-service?authSource=admin